// Code generated by protoc-gen-tron. DO NOT EDIT.
// source: tx-example/api/auth/v1/auth.proto

package auth

import (
	"context"
	"embed"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/loghole/tron/transport"
	"google.golang.org/grpc"
)

//go:embed auth.swagger.json
var swagger embed.FS

// AuthAPIServiceDesc is description for the AuthAPIServer.
type AuthAPIServiceDesc struct {
	svc AuthAPIServer
}

func NewAuthAPIServiceDesc(s AuthAPIServer) transport.ServiceDesc {
	return &AuthAPIServiceDesc{svc: s}
}

func (d *AuthAPIServiceDesc) RegisterGRPC(s *grpc.Server) {
	RegisterAuthAPIServer(s, d.svc)
}

func (d *AuthAPIServiceDesc) RegisterHTTP(mux *runtime.ServeMux) {
	RegisterAuthAPIHandlerServer(context.Background(), mux, d.svc)
}

func (d *AuthAPIServiceDesc) SwaggerDef() []byte {
	b, _ := swagger.ReadFile("auth.swagger.json")

	return b
}
