// Generated by protoc-gen-tron.

package auth

import (
	"context"
	"fmt"
	"strings"

	"github.com/gadavy/tx-example/internal/app/domain"
	auth "github.com/gadavy/tx-example/pkg/api/auth/v1"
	"google.golang.org/grpc/metadata"
)

func (i *Implementation) SignUp(
	ctx context.Context,
	req *auth.SignUpReq,
) (*auth.SignUpResp, error) {
	params := &domain.SignUpParams{
		Email:    req.Email,
		Password: req.Password,
	}

	md, ok := metadata.FromIncomingContext(ctx)
	if ok {
		params.IP = strings.Join(md.Get("x-forwarded-for"), ", ")
		params.Useragent = strings.Join(md.Get("user-agent"), ", ")
	}

	if err := i.service.SignUp(ctx, params); err != nil {
		i.logger.Error(ctx, err)

		return nil, fmt.Errorf("sign up: %w", err)
	}

	return &auth.SignUpResp{}, nil
}
