// Generated by protoc-gen-tron.

package auth

import (
	"context"
	"fmt"

	"github.com/gadavy/tx-example/internal/app/domain"
	auth "github.com/gadavy/tx-example/pkg/api/auth/v1"
)

func (i *Implementation) SignOut(
	ctx context.Context,
	req *auth.SignOutReq,
) (*auth.SignOutResp, error) {
	session, ok := domain.SessionFromContext(ctx)
	if !ok {
		return nil, domain.ErrForbidden
	}

	if err := i.service.SignOut(ctx, session); err != nil {
		i.logger.Error(ctx, err)

		return nil, fmt.Errorf("sign out: %w", err)
	}

	if err := i.setGRPCCookie(ctx, "", true); err != nil {
		return nil, err
	}

	return &auth.SignOutResp{}, nil
}
