// Generated by protoc-gen-tron.

package auth

import (
	"context"
	"fmt"
	"strings"

	"github.com/gadavy/tx-example/internal/app/domain"
	auth "github.com/gadavy/tx-example/pkg/api/auth/v1"
	"google.golang.org/grpc/metadata"
)

func (i *Implementation) SignIn(
	ctx context.Context,
	req *auth.SignInReq,
) (*auth.SignInResp, error) {
	params := &domain.SignInParams{
		Email:    req.Email,
		Password: req.Password,
	}

	md, ok := metadata.FromIncomingContext(ctx)
	if ok {
		params.IP = strings.Join(md.Get("x-forwarded-for"), ", ")
		params.Useragent = strings.Join(md.Get("user-agent"), ", ")
	}

	session, err := i.service.SignIn(ctx, params)
	if err != nil {
		i.logger.Error(ctx, err)

		return nil, fmt.Errorf("sign in: %w", err)
	}

	if err := i.setGRPCCookie(ctx, session.Token, false); err != nil {
		return nil, err
	}

	return &auth.SignInResp{}, nil
}
